name: build-all

on:
  #keep manual for now
  push:
    branches:
      - main
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.event.repository.name }}/portmaster

concurrency: 
  group: main

jobs:
  buildx:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get date for artifacts
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H%M')"
  
      - name: Build and push Docker image
        id: build
        run: |
           set -e
           ./init-docker
           docker buildx use portmaster-remote-builder
           ./ports/build-base-images --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64   
           ./ports/build-all --push --docker-image
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: "Publish pre-release: ${{github.event.inputs.release_tag}}"
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name:  "${{steps.date.outputs.date}}"
          name: "${{steps.date.outputs.date}}"
          files: |
            release/*.zip
            ports.md
          token: ${{ secrets.GITHUB_TOKEN }}
