name: build-all

on:
  #keep manual for now
  push:
    branches:
      - main
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.event.repository.name }}/portmaster

jobs:
  buildx:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        run: |
           set -e
           ./init-docker
           docker buildx create --name multi-platform --driver docker-container --use
           ./ports/build-base-image --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64   
           ./ports/build-all --push --docker-image
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: all-ports
          path: |
            release/*.zip
