name: release-ports
on:
  #keep manual for now
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        description: "The git tag to create for this release"
       
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.event.repository.name }}/portmaster

jobs:
  buildx:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        run: |
           set -e
           ./init-docker
           docker buildx use portmaster-remote-builder
           #./ports/build-all --docker-image

      - name: "Publish release: ${{github.event.inputs.release_tag}}"
        uses: ncipollo/release-action@v1
        with:
          tag:  "${{github.event.inputs.release_tag}}-test"
          body: |
            # Release Notes
              TBD
            
          artifacts: "version"
          token: ${{ secrets.GITHUB_TOKEN }}
          

